# Generated by Django 3.2.9 on 2021-11-26 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 26, 15, 29, 35, 646347, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 26, 15, 29, 38, 889011, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
